name: Build and deploy to Test PyPI

on:
    workflow_dispatch:
    pull_request:
    push:
      branches:
        - main
    release:
      types:
        - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.18.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: cp36-* cp37-* *musllinux*
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y autoconf automake curl libtool pkgconfig sudo &&
            git clone https://github.com/openvenues/libpostal &&
            cd libpostal &&
            git checkout tags/v1.1 &&
            ./bootstrap.sh && 
            ./configure --disable-data-download --disable-sse2 && 
            make -j4 && 
            sudo make install &&
            sudo ldconfig &&
            pkg-config --cflags libpostal && 
            pkg-config --libs libpostal && 
            pkg-config --cflags --libs libpostal
          CIBW_BEFORE_ALL_MACOS: >
            brew install autoconf automake curl libtool pkg-config &&
            git clone https://github.com/openvenues/libpostal &&
            cd libpostal &&
            git checkout tags/v1.1 &&
            ./bootstrap.sh && 
            ./configure --disable-data-download --disable-sse2 && 
            make -j4 && 
            sudo make install && 
            pkg-config --cflags libpostal && 
            pkg-config --libs libpostal && 
            pkg-config --cflags --libs libpostal

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
  
        - uses: actions/setup-python@v5
  
        - name: Build sdist
          run: pipx run build --sdist
          env:
            CIBW_BEFORE_ALL: >
              yum install -y autoconf automake curl libtool pkgconfig sudo &&
              git clone https://github.com/openvenues/libpostal &&
              cd libpostal &&
              git checkout tags/v1.1 &&
              ./bootstrap.sh && 
              ./configure --disable-data-download --disable-sse2 && 
              make -j4 && 
              sudo make install &&
              sudo ldconfig &&
              pkg-config --cflags libpostal && 
              pkg-config --libs libpostal && 
              pkg-config --cflags --libs libpostal
        
        - uses: actions/upload-artifact@v4
          with:
            name: cibw-sdist
            path: dist/*.tar.gz


  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
        id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
            pattern: cibw-*
            path: dist
            merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/